### ISSUE TITLE
Got error when running scripts/generation/llama_h2o.sh 

### ISSUE THREAD

**Issue by ThisisBillhe** [FMInference/H2O#22]
I generate context with full cache successfully, but get error generating with H2O cache: 
Specifically, I only modified this line to save gpu memory: 
`checkpoint = copy.deepcopy(model.cpu().state_dict())`

```
Traceback (most recent call last):
  File "run_text_generation.py", line 163, in <module>
    main()
  File "run_text_generation.py", line 156, in main
    generate_ids_hh = model.generate(input_ids, max_new_tokens=args.length)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/transformers/generation/utils.py", line 1479, in generate
    return self.greedy_search(
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/transformers/generation/utils.py", line 2340, in greedy_search
    outputs = self(
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1183, in forward
    outputs = self.model(
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1070, in forward
    layer_outputs = decoder_layer(
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 798, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hyf/H2O/h2o_hf/utils_hh/modify_llama.py", line 83, in forward
    kv_seq_len += past_key_value[0].shape[-2]
  File "/home/hyf/anaconda3/envs/torch211/lib/python3.8/site-packages/transformers/cache_utils.py", line 78, in __getitem__
    raise KeyError(f"Cache only has {len(self)} layers, attempted to access layer with index {layer_idx}")
KeyError: 'Cache only has 0 layers, attempted to access layer with index 0'
```

**Comment by Yogurt2019** [comment]
pip install transformers==4.35.2 solved the problem.
The author should add the versions or pip requirements.txt into README.md.
